{% set name = "nwb2bids" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49c1ac6aebde3fe5bb621724adb6d5f301f1cc6f6ad9d1c130ab222ba9ba71f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - nwb2bids = nwb2bids._command_line_interface._main:_nwb2bids_cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - pandas
    - pynwb
    - rich-click
    - pydantic
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
  source_files:
    - tests
  imports:
    - nwb2bids
  commands:
    - pytest -m "not remote" -c pyproject.toml

about:
  home: https://github.com/con/nwb2bids
  summary: Reorganize NWB files into a BIDS directory layout.
  description: |
    Currently developed for the microephys BIDS modality, which encompasses both the NWB ecephys and icephys
    neurodata subtypes, and which is currently pending formal inclusion in BIDS schema as part of BEP032.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://nwb2bids.readthedocs.io
  dev_url: https://github.com/con/nwb2bids

extra:
  recipe-maintainers:
    - CodyCBakerPhD
    - yarikoptic
    - candleindark
    - asmacdo
